name: Build Thesis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: _Diplomarbeit.tex
          working_directory: thesis
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: _Diplomarbeit.pdf
